# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5755a98d8960bb53f26089461a92d67a6ea66bfadf322953ce3da52cf85a7739afafc8891d9be5b1fd9d264466f65080ce04da2b2bdd226b5fb976b0cbd0544f

test:
  secret_key_base: 9a2bd269dda3c64edad6df631d5b59ed1e8cd8eb0218c817622667cd9ca0a3d35fac8329dce9fe189487cc1e7be2de7c10656556aaef03ef2278967b87e77dcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
